### Index
GET {{ app_url }}/logbook/entries
Accept: application/json
Authorization: Bearer {{ token }}

### Store
POST {{ app_url }}/logbook/entries
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "mood": "ok",
    "weather": "sunny",
    "latitude": 30,
    "longitude": 60,
    "supplies_for_days": 30,
    "note": "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering."
}